"""
ingest_data.py
--------------
Ingests raw student data into PostgreSQL for historical/analysis use.
This is NOT required for training — the model trains directly from
refined_training_data.csv (generated by refined_data.py).

This script maps a source CSV into the `academic_records` table which
can be used for additional analytics.
"""

import pandas as pd
from app.database import engine


def clean_and_ingest(file_path: str):
    # 1. Load data
    df = pd.read_csv(file_path)
    print(f"Loaded {len(df):,} rows from {file_path}")

    # 2. Generate Student IDs
    df["student_id"] = [f"STU-{i+1:04d}" for i in range(len(df))]

    # 3. Map source columns → project feature names
    #    Adjust these mappings if your source CSV uses different headers.
    rename_map = {
        "Hours Studied":                        "cat_score",         # closest proxy
        "Previous Scores":                       "prev_mean_grade",
        "Attendance":                            "attendance_rate",
        "Extracurricular Activities":            "_ext",             # temp col
        "Performance Index":                    "final_score",
    }
    df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})

    # HELB status: derive from extracurricular column if present, else default 0
    if "_ext" in df.columns:
        df["helb_status"] = df["_ext"].map({"Yes": 1, "No": 0}).fillna(0).astype(int)
        df = df.drop(columns=["_ext"])
    else:
        df["helb_status"] = 0

    # Ensure required columns exist; fill missing with 0
    for col in ["attendance_rate", "cat_score", "prev_mean_grade", "helb_status", "final_score"]:
        if col not in df.columns:
            df[col] = 0.0

    # 4. Select final columns
    final_df = df[["student_id", "attendance_rate", "cat_score",
                   "prev_mean_grade", "helb_status", "final_score"]]

    # 5. Ingest
    print("Ingesting into PostgreSQL (table: academic_records)…")
    final_df.to_sql("academic_records", con=engine, if_exists="replace", index=False)
    print(f"✅  Done. {len(final_df):,} records ingested.")


if __name__ == "__main__":
    clean_and_ingest("Data/Student_Performance.csv")