from pydantic import BaseModel, Field, ConfigDict
from typing import Optional

class StudentBase(BaseModel):
    # Identity Fields (New)
    student_name: str
    reg_no: str
    
    # Original Features
    student_id: Optional[str] = None # Keep as optional if using reg_no as primary
    study_hours: float = Field(ge=0, le=168)
    prev_mean_grade: float = Field(ge=0, le=100)
    helb_status: bool = False # Default to False if not sent by React
    sleep_hours: float = Field(ge=0, le=24)
    revision_intensity: int = Field(ge=1, le=10) # 1-10 Scale
    target_mean_score: Optional[float] = Field(None, ge=0, le=100)

    model_config = ConfigDict(from_attributes=True)

# This is what we use for the POST /predict request
class StudentCreate(StudentBase):
    pass

# This is what we return (includes the ID generated by PostgreSQL)
class StudentResponse(StudentBase):
    id: int